create table offer
(
    id          bigint generated by default as identity,
    amount      float  not null,
    status      varchar(255),
    customer_id bigint not null,
    picture_id  bigint not null,
    salesman_id bigint not null,
    primary key (id)
);
create table picture
(
    id          bigint generated by default as identity,
    description varchar(3000),
    file_path   varchar(255) not null,
    name        varchar(255) not null,
    price       float,
    creator_id  bigint       not null,
    owner_id    bigint       not null,
    primary key (id)
);
create table user
(
    id               bigint generated by default as identity,
    email            varchar(255) not null,
    nickname         varchar(255) not null,
    password         varchar(255) not null,
    user_description varchar(4000),
    wallet           float,
    profile_picture   varchar(255),
    primary key (id)
);
create table user_role
(
    user_id bigint not null,
    roles   varchar(15)
);
alter table offer
    add constraint offer_customer_fk foreign key (customer_id) references user;
alter table offer
    add constraint offer_picture_fk foreign key (picture_id) references picture;
alter table offer
    add constraint offer_salesman_fk foreign key (salesman_id) references user;
alter table picture
    add constraint picture_creator_fk foreign key (creator_id) references user;
alter table picture
    add constraint picture_owner_fk foreign key (owner_id) references user;
alter table user_role
    add constraint user_role_user_fk foreign key (user_id) references user